```{r}
devtools::install_github('bbc/bbplot')
library(scales)
```


### Plots colours

```{r}
# theme of choice:
theme_bw()

# Colours:
colour1 = '#009988'
colour2 = '#1380A1'
colour3 = 'orange'
colour4 = '#333333'
colour5 = 'grey88'
colour6 = 'royalblue4'
colour7 = 'coral3'
colour8 = '#76b8a9'

# Find colour gradient:
colfunc <- colorRampPalette(c("#009988", "#993366", '#1380A1')
colfunc(10)
plot(rep(1,10),col=colfunc(10),pch=19,cex=3)

```

### Title sizes
```{r}

# If a plot will end up in a panel
plot.title = element_text(size = 12, face = 'bold',  hjust = 0.5)  # center aligned

# If a plot is single standing
plot.title = element_text(size = 15, face = 'bold') 
```


### Decisions
```{r}
#'Non-responder vs Responder'--> vs no not, hiphen, singular, only initial is capital
```



### Single plots
```{r}
# Do the 'meat' of the plot first
repl2_barplot <- ggplot(repl_sample_2, aes(x = -log10(NOM.p.val), y = reorder(NAME, -NOM.p.val   #arrange y based on diff col
  geom_bar(stat = "identity", color="#1380A1") +
  geom_point(aes(size = SIZE, color = good_FDR == 'YES'))+   # point color changes based on col good_FDR
    scale_color_manual(name = 'FDR < 25%', values= setNames(c("coral3", "grey"), c(T, F))) +

# Theme and fine tuning
repl2_barplot
  + geom_hline(yintercept = 25, linewidth = 0.5, colour="coral3", lty=2)  # this makes a dashed horizontal line
  + geom_hline(yintercept = 0, linewidth = 1, colour="#333333")   # this makes heavier bottom
  + bbc_style()
  + guides(color=FALSE) # eliminates legend about colour
  + geom_text_repel(aes(label = label, color = diff_expressed), max.overlaps = Inf, show.legend=FALSE)
  + scale_alpha_manual(values=c(0.1, 0.3, 0.6, 0.8, 1))+
  + labs(title="Spread CV for sample 2",
          subtitle = "Variance across 3 technical replicates",
          y = "CV (%)",
          x = 'Proteins (1797 unique)',
         color = "Differentially expressed") 
  + scale_y_continuous(breaks=c(0, 25, 50, 100, 200))# this adds automatic ticks 
  + scale_color_manual(values=c("royalblue4", "black", "coral3"), labels = c("Down-regulated", "Non significant", "Up-regulated")) #color spec
  + theme(
      plot.title = element_text(size = 15, face = 'bold', vjust = -8),
      plot.title = element_text(hjust = 0.5),   # centers title
      plot.subtitle = element_text(size = 12, vjust = -8),
      axis.text.x = element_blank(),    # eliinates x-axis ticks 
      axis.title.x = element_text(size = 10),
      axis.title.y = element_text(size = 10),
      axis.text.y = element_text(size = 8),
      axis.ticks.x = element_blank(),
      legend.position="top",
      legend.direction = 'horizontal'
      strip.text = element_text(colour = 'white', face = 'bold'),   # this changes font inside facet_wrap rectangle
      strip.background =element_rect(fill="royalblue4"))   # this changes backgorund colour facet_wrap rectangle
  +     guides(color = guide_legend(
        override.aes=list(shape = 18)))  # this makes the legend icons rombi instead of circles
  + facet_wrap(~ Sample_nr, scales ="free", ncol=1) #'free_y', ncol=1 sets it vertical

small_legend_theme <- theme(legend.text = element_text(size = 12), 
                                  legend.title = element_text(size = 14), 
                                  legend.key.size = unit(2, 'cm'))

```


### Panel with multiple plots

```{r}
top10_set2 <-  ggplot(set2_top10_genes, aes(x=reorder(Gene.Name, -Set2_Peptide.count), y=Set2_Peptide.count)) + 
  geom_bar(stat = "identity") +
  geom_text(aes(label = Set2_Peptide.count), vjust = -0.6) +
  xlab("Gene names") + 
  ylab('Peptide count') +
  ylim(0, 900) +
  ggtitle('Set 2')+
  # theme(plot.title = element_text(size = 10, face = "bold", colour = "#333333"))

# Let title not be bold, if there will be a common title to both plots.
```



### Combine them all ###

```{r}
# Prefer
plot <- ggarrange(repl2_barplot, repl9_barplot, common.legend = TRUE)

plot_ann <- annotate_figure(plot, top = text_grob("CV distribution for the two samples with replicates", 
               color = "#333333", face = "bold", size = 15))

# alternative
library(patchwork)
layout <- top10_set1 / top10_set2  / top10_set3 
layout &  theme(plot.tag = element_text(size = 14))
```

### Save
```{r}

ggsave(path = "C:/Users/1aria/Desktop/rep/Output/Plots", filename = "CV_sample2_and_9.png",plot,height=15,width=17,units="cm",dpi=200)

```


### Alternative combination
```{r}
# From lund qorkshop
title <- ggdraw() + 
  draw_label(
    "QQ plot of 9 randomly selected genes",
    fontface = 'bold',
    x = 0,
    hjust = 0) +  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

```


```

