---
title: "Make Volcano plot"
output: html_notebook
editor_options: 
  
  chunk_output_type: inline
---
# Admin
```{r}
old.packages()    # tells me which pack are old
update.packages(ask = FALSE)
library(tidyverse)
```

Load my material (means only)
```{r}

load("C:/Users/1aria/Desktop/rep/Data/Output_data/wide_matrix_t_means.Rda")
Metatable_means <- read_excel("C:/Users/1aria/Desktop/rep/Data/Metadata/Metatable_means.xlsx", sheet = "w nur")

# remove batch 1
wide_matrix_t_means_no_batch1 <- wide_matrix_t_means %>% select(-contains(c('NR_13', 'NR_14', 'NR_15', 'NR_16', 'NR_17', 'NR_18')))

```


### Nidhi's t test function --> DONT RUN
```{r}

diff_exp = function(dataset, condA, condB) {
  results = apply(dataset, 1, function(x) t.test(x[condA], x[condB]))
  
  p.val = list()
  for(i in names(results)) {p.val[[i]] = results[[i]]$p.value}
  p = as.vector(unlist(p.val))
  
  fc = rowMeans(dataset[,condA])-rowMeans(dataset[,condB])
  
  res = as.data.frame(cbind(names(results), fc, p))
  colnames(res) = c("Protein", "log2fc", "p.value")
  
  res$adj.p.value = p.adjust(res$p.value, method="fdr")
  
  res$Gene_Name = data$X[match(res$Protein, data$geneid)]
  
  res
}

```

# Tweaking above diff_expression function (works! RUN THIS ONE)
```{r}
# Provide: 
# dataset: numerical only df with genes on rows and samples as col
# colnames_conditionA/B: list containing names of all cols of interest (eg NR vs R)

diff_exp = function(dataset, colnames_conditionA, colnames_conditionB) {
  results = apply(dataset, 1, function(x) t.test(x[colnames_conditionA], x[colnames_conditionB]))
  
  colindex_conditionA <-which(colnames(dataset) %in% colnames_conditionA)
  colindex_conditionB  <-which(colnames(dataset) %in% colnames_conditionB)
  
  
  p.val = list()
  for(i in names(results)) {p.val[[i]] = results[[i]]$p.value}
  p_value = as.vector(unlist(p.val))
  
  log2_fc = rowMeans(dataset[colindex_conditionA])-rowMeans(dataset[colindex_conditionB])
  
  t_test_result = as.data.frame(cbind(names(results), log2_fc, p_value))
  colnames(t_test_result) = c("Protein", "log2_fc", "p_value")
  
  t_test_result$adj_p_value = p.adjust(t_test_result$p_value, method="fdr")
  
  # t_test_result$Gene_Name = data$X[match(res$Protein, data$geneid)]
  
  t_test_result
}
```




### Diff expression of R vs NR
```{r}
# Define conditions -->  colnames of R vs NR
NR_colnames <- Metatable_means %>% filter(Sample_status == 'NR') %>% select(Sample_name) %>% as.list() %>% unlist()
R_colnames <- Metatable_means %>% filter(Sample_status == 'R') %>% select(Sample_name) %>% as.list() %>% unlist()

# Run function
NR_vs_R_results = as.data.frame(diff_exp(wide_matrix_t_means_no_batch1, colnames_conditionA =NR_colnames, colnames_conditionB =R_colnames ))

# Which proteins are diff expressed? (adj p below 0.05?)
significant_NR_vs_R = NR_vs_R_results %>% na.omit()  %>%  filter(adj_p_value<0.05)  # 18 proteins are signid different expressed


# expand results so that easier to make volcano plot - add cols with additionak info
NR_vs_R_results_expanded <- NR_vs_R_results   %>% 
  na.omit() %>%
  mutate_at(c('log2_fc', 'p_value', 'adj_p_value'), as.numeric) %>%
  mutate(diff_expressed = "NO") %>%
  mutate(diff_expressed = if_else(condition = (log2_fc > 0.5 & adj_p_value < 0.05) , true = "UP", false = diff_expressed )) %>%
  mutate(diff_expressed = if_else(condition = (log2_fc < -0.5 & adj_p_value < 0.05) , true = "DOWN", false = diff_expressed ))   %>%
  mutate(label = NA ) %>%
  mutate(label = if_else(condition = (diff_expressed != "NO"), true = Protein, false = label))



volc1 <- ggplot(data=NR_vs_R_results_expanded, aes(x=log2_fc, y=-log10(adj_p_value))) + 
  geom_point(size = 3, aes(colour=diff_expressed)) +
  theme_bw() + 
  geom_vline(xintercept=c(-0.5, 0.5), col="grey60") +
  geom_hline(yintercept=-log10(0.05), col="grey60") +
  geom_vline(xintercept=c(0, 0), col="grey81",lty = 3 ) +
  scale_color_manual(values=c("royalblue4", "black", "coral3"), labels = c("Down-regulated", "Non significant", "Up-regulated")) +
  geom_text_repel(aes(label = label, color = diff_expressed), max.overlaps = Inf) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position = 'bottom',
        plot.title = element_text(size = 15, face = 'bold')) +
  labs(title= 'Volcano plot - Non responders vs responders', color = "Differentially expressed", x = 'log2(fold change)', y= '- log10(p-value)')

volc1
  
```


## This works, from intenet
```{r}
library(dplyr)

Volc_plot_data_raw <- res %>% select(c('fc', 'adj.p.value'))


Volc_plot_data <- 
  Volc_plot_data_raw %>%
  mutate_if(is.character, as.numeric) %>%
  na.omit() %>%
  # mutate("-log10_p" = -log10(adj.p.value)) %>%
  rownames_to_column('Gene_Name')
# 1298 total genes after eliminating NAs

# Specify is up or down regulated in a diff column

Volc_plot_data$diffexpressed <- "NO"
Volc_plot_data$diffexpressed[Volc_plot_data$fc > 0.6 & Volc_plot_data$adj.p.value < 0.05] <- "UP"
Volc_plot_data$diffexpressed[Volc_plot_data$fc < -0.6 & Volc_plot_data$adj.p.value < 0.05] <- "DOWN"

Volc_plot_data$delabel <- NA
Volc_plot_data$delabel[Volc_plot_data$diffexpressed != "NO"] <- Volc_plot_data$Gene_Name[Volc_plot_data$diffexpressed != "NO"]

# plot
p <- ggplot(data=Volc_plot_data, aes(x=fc, y=-log10(adj.p.value), col=diffexpressed, label=delabel)) + geom_point() + theme_minimal() +
    geom_vline(xintercept=c(-0.6, 0.6), col="red") +
    geom_hline(yintercept=-log10(0.05), col="red") +
  scale_color_manual(values=c("blue", "black", "red")) +
  geom_text_repel(max.overlaps = Inf)
  # xlim(c(-20, 20))+
  # ylim(c(1, 2))

p

```





















On my data
```{r}
# My code




r1 = colnames(wide_matrix_t_means_no_batch1[, c(1:5)])

t_test_results = diff_exp(wide_matrix_t_means_no_batch1, condition_NR2_names, condition_R2_names)

# Nidhis code
#r1 = grep("LC_EVs", colnames(input_ev))   #AM:this gives index of cols w the LC_Evs
#r2 = grep("MM_EVs", colnames(input_ev))

--

r1 = colnames(input_ev[,c(1:4,10)])    #AM: this gives me tha neames of the cols that matched the condition above
r2 = colnames(input_ev[,5:9,11])

results = data.frame(diff_exp(input_ev, r2, r1))

results_sig = results[which(results$adj.p.value<0.05),]

write.csv(results,"HiRIEF/Cancer/EV/EV_LUADvsMM_t-test_excludingS1.csv")
```

