---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

## Jojo code for limma- add cycle and responder column
```{r}
wide_dat <-
    filt_combined %>% 
    select(DAid,Assay,NPX,Disease,Age,Sex) %>% 
    spread(Assay,NPX,-1) 
  
  all_data <- wide_dat
  all_data <-
    all_data %>% 
    mutate(Disease = ifelse(Disease == cancer, paste("1_", cancer, sep = ""), paste("0_", Disease, sep = "")))
  
  design<-model.matrix(~0 + all_data$Age + all_data$Sex + all_data$Disease)
  colnames(design) <- c('Age', "Female","Male",as.character(cancer))
  
  fit <- all_data %>% 
    select(-DAid,-Sex,-Age,-Disease) %>%
    t() %>% 
    lmFit(design=design)
  
  contrast <- makeContrasts(as.character(cancer), levels=design)
  
  # apply contrast
  contrast_fit<-contrasts.fit(fit, contrast)
  
  # apply empirical Bayes smoothing to the SE
  ebays_fit<-eBayes(contrast_fit)
  
  # summary
  print(summary(decideTests(ebays_fit)))
```

```{r}
run_limma_IGT <- function(input_cancer,input_ctrl,cancer){
  
  one_cancer <- filter(input_cancer,Disease==cancer)
  filt_combined <- rbind(input_ctrl,one_cancer)
  filt_combined <- filter(filt_combined,Age>0)
  
  wide_dat <-
    filt_combined %>% 
    select(DAid,Assay,NPX,Disease,Age,Sex) %>% 
    spread(Assay,NPX,-1) 
  
  all_data <- wide_dat
  all_data <-
    all_data %>% 
    mutate(Disease = ifelse(Disease == cancer, paste("1_", cancer, sep = ""), paste("0_", Disease, sep = "")))
  
  design<-model.matrix(~0 + all_data$Age + all_data$Sex + all_data$Disease)
  colnames(design) <- c('Age', "Female","Male",as.character(cancer))
  
  fit <- all_data %>% 
    select(-DAid,-Sex,-Age,-Disease) %>%
    t() %>% 
    lmFit(design=design)
  
  contrast <- makeContrasts(as.character(cancer), levels=design)
  
  # apply contrast
  contrast_fit<-contrasts.fit(fit, contrast)
  
  # apply empirical Bayes smoothing to the SE
  ebays_fit<-eBayes(contrast_fit)
  
  # summary
  print(summary(decideTests(ebays_fit)))
  # extract DE results
  DE_results<-topTable(ebays_fit, n=ncol(all_data), adjust.method="fdr", confint=TRUE)
  
  DE_results <- DE_results %>% 
    mutate(
      Expression = case_when(logFC > 1 & -log10(adj.P.Val) >1.3 ~ "Up-regulated",
                             logFC < 1 & -log10(adj.P.Val) >1.3 ~ "Down-regulated",
                             TRUE ~ "Unchanged"))
  sig_genes <- DE_results %>% 
    filter(Expression != 'Unchanged') %>% 
    arrange(desc(-log10(adj.P.Val)), desc(abs(logFC)))
  sig_genes <- mutate(sig_genes,term = rownames(sig_genes))
  top_10_sig <- head(sig_genes,n=10)
  top <- 10
  top_up <- DE_results %>% 
    filter(Expression == 'Up-regulated') %>% 
    arrange(desc(-log10(adj.P.Val)), desc(abs(logFC))) %>% 
    head(top)
  top_down <- DE_results %>% 
    filter(Expression == 'Down-regulated') %>% 
    arrange(desc(-log10(adj.P.Val)), desc(abs(logFC))) %>% 
    head(top)
  
  top_genes <- rbind(top_up,top_down)
  
  volcano_plot <- DE_results %>% 
    ggplot(aes(logFC,-log10(adj.P.Val)))+
    geom_point() +
    theme_bw() +
    ggtitle(paste(cancer))
  
  volcano_plot <- volcano_plot +
    geom_label_repel(data = top_up,
                     mapping = aes(logFC, -log10(adj.P.Val), label = rownames(top_up)),
                     size = 2)
  
  return(list(DE_results = DE_results,
              sig_genes = sig_genes,
              ebays_fit = ebays_fit,
              top_10_prots = top_10_sig,
              top_genes = top_genes,
              top_up = top_up,
              top_down = top_down,
              volcano_plot = volcano_plot))
}
```

