---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
fig_width: 15
fig_height: 17
---

follow: <https://core.ac.uk/reader/216334901?utm_source=linkout>

### Load the protein abundance wide df and metadata

NB: Previously, we turned NAs into 0s (Alternative approaches I saw used are to infer NAs using BAyesian methods. Which should be more accurate.)

### Make a PCA object + scree plot

```{r}
# PCA object
wide_matrix_no_NAs_select <- wide_matrix_no_NAs %>% select(-c(1:9))
results.pca <-prcomp(wide_matrix_no_NAs_select[,],scale=TRUE,retx=TRUE)

# Scree plot
frac_var <- function(x) x^2/sum(x^2)
library(scales)

results.pca$sdev %>% 
  as_tibble() %>% 
  frac_var() %>% 
  mutate(Comp = colnames(results.pca$x)) %>% 
  slice(1:9) %>% 
  ggplot(aes(x=Comp, y = value)) + 
  geom_bar(stat = "identity", fill = "#4DC5F9") +
  geom_hline(yintercept = 0.03, linetype=2) +
  xlab("Principal Components") +
  scale_y_continuous(name = "Variance Explained", breaks = seq(0,0.8,0.1), labels = percent_format(accuracy = 5L)) +
  theme_classic(base_size = 14)
```

### Make a PCA plot

```{r}
results_pca_all <- results.pca$x %>%
  as.data.frame() %>%
  rownames_to_column(var = "Sample_name") %>%
  full_join(Metatable, by = "Sample_name")

ggplot(results_pca_all, aes(x=PC1, y=PC2, color = Sample_nr)) +
  geom_point(size = 3,  aes(shape = Cycle)) +
  geom_vline(xintercept = 0, linetype=2) +
  geom_hline(yintercept = 0, linetype=2) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())

plot(results.pca)

```

### Heatmap

```{r}
pheatmap(t(wide_matrix_no_NAs),scale="row",show_rownames=FALSE)

pheatmap(t(wide_matrix),scale="row",show_rownames=FALSE)

```
