---
title: "Analysis of technical replicates"
output: html_notebook
editor_options: 
  
  chunk_output_type: inline
fig_width: 15 
fig_height:17 
---

Sample 9 and sample 2 were processed in parallel, in triplicate, to assess how much variability the sample processing introduces.

Here, I am analyzing this, by checking CV% across replicates.

# Admin

```{r}
old.packages()    # tells me which pack are old
update.packages(ask = FALSE)
```

# Relevant packages
```{r}
library(readxl)
library(tidyverse)
devtools::install_github('bbc/bbplot')
library(scales)
```

# Load material
```{r}
load("~/MTLS/rep/Data/Output_data/wide_matrix.RDa")    # this is a purely numerical matrix with samples on rows, prot on cols
Metatable <- read_excel('~/MTLS/rep/Data/Metadata/Metatable.xlsx')
load("~/MTLS/rep/Data/Output_data/info_to_analyze.Rda")   # this df contains samples on rows, col both prot and info

wide_matrix_t<- as.data.frame(t(wide_matrix))
```

# Extract replicates only
```{r}
# Name of replicate samples
sample_2_IDs <- c('R_2_SCR_R1_Set1_tmt16plex_131N', 'R_2_SCR_R2_Set1_tmt16plex_132N', 'R_2_SCR_R3_Set1_tmt16plex_133N')
sample_9_IDs <- c('NR_9_SCR_R1_Set2_tmt16plex_127C', 'NR_9_SCR_R2_Set2_tmt16plex_128C', 'NR_9_SCR_R3_Set2_tmt16plex_129C')

wide_matrix_t_repl <- wide_matrix_t %>% select(c(sample_2_IDs, sample_9_IDs))

repl_sample_2 <- wide_matrix_t_repl %>% select(all_of(sample_2_IDs))
repl_sample_9 <- wide_matrix_t_repl %>% select(all_of(sample_9_IDs))

```

### Calc means
```{r}
repl_sample_2$mean <- rowMeans(repl_sample_2, na.rm=T)
repl_sample_9$mean <- rowMeans(repl_sample_9, na.rm=T)

repl_sample_2$sd <- apply(repl_sample_2, 1, sd, na.rm=TRUE)
repl_sample_9$sd <- apply(repl_sample_9, 1, sd, na.rm=TRUE)
```

### Calc CV (Nidhi's formula)
```{r}
### The formula: SQRT(EXP(STDEV(X:Z)^2)-1)*100

CV <- function(x) {sqrt(exp(x**2)-1)*100}

CV_2 <- lapply(repl_sample_2[c('sd')], CV)  # calcs CV on sd value
CV_9 <- lapply(repl_sample_9[c('sd')], CV)  # calcs CV on sd value

repl_sample_2$CV <- CV_2$sd   # adds cv as a col
repl_sample_9$CV <- CV_9$sd   # adds cv as a col

```

### Plot CVs
```{r}
repl_sample_2 <- tibble::rownames_to_column(repl_sample_2, "Protein")
repl_sample_9 <- tibble::rownames_to_column(repl_sample_9, "Protein")

repl2_barplot <- ggplot(repl_sample_2, aes(x=Protein, y = CV )) +
  geom_bar(stat = "identity", color="#1380A1") 


repl2_barplot +
  geom_hline(yintercept = 25, linewidth = 0.5, colour="red", lty=2) +
  geom_hline(yintercept = 0, linewidth = 1, colour="#333333")+
 bbc_style() +
  labs(title="Spread CV for sample 2",
       subtitle = "Variance across 3 technical replicates",
       y = "CV (%)",
       x = 'Proteins (1797 unique)') +
   scale_y_continuous(breaks=c(0, 25, 50, 100, 200)) +
  theme(plot.title = element_text(size = 15, face = 'bold', vjust = -8), plot.subtitle = element_text(size = 12, vjust = -8), axis.text.x = element_blank(), axis.title.x = element_text(size = 10),  axis.title.y = element_text(size = 10), axis.text.y = element_text(size = 8))
```


```{r}

### What I did before (15th Apr 2023)
info_replicates <- info_to_analyse %>% filter(Replicate %in% c(1,2,3))   # generate df

# CV
replicates_cv <- info_replicates %>% group_by(Sample_nr) %>% select(12:1797) %>% sapply(function(x) sd(x, na.rm=T) / mean(x, na.rm=T) * 100)

replicates_cv <- info_replicates %>% group_by(Sample_nr) %>% summarise(across(12:1796, function(x) sd(x, na.rm=T) / mean(x, na.rm=T) * 100))
  

hist.data.frame(replicates_cv[ , c(89, 178, 1022, 765, 453, 88)], nclass = 5)
```

